
# VRF variables
vrf_base_name: "VRF"
vrf_base_id: 1
vrf_count: 50
rd_base: "65000"
vrfs: "{{ range(vrf_base_id, vrf_base_id + vrf_count) | map('regex_replace', '^', vrf_base_name) | list }}"
rds: "{{ range(vrf_base_id, vrf_base_id + vrf_count) | map('string') | map('regex_replace', '^', rd_base + ':') | list }}"

# VLAN variables
vlan_base_id: 1
vlan_count: 50
vlans: "{{ range(vlan_base_id, vlan_base_id + vlan_count) | list }}"
vlan_descriptions: "{{ range(vlan_base_id, vlan_base_id + vlan_count) | map('regex_replace', '^', 'VLAN_') | list }}"
