---
- name: Verify VRF and VLAN configurations on Arista EOS devices
  hosts: arista_node
  gather_facts: no
  vars_files:
    - variable.yml

  tasks:
    - name: Check VRF configurations
      arista.eos.eos_command:
        commands:
          - show vrf
      register: show_vrf_output

    - name: Validate VRF configurations
      set_fact:
        vrf_results: "{{ vrf_results + [item ~ ' - configuration ' ~ ('OK' if item in show_vrf_output.stdout[0] else 'Fail')] }}"
      loop: "{{ range(vrf_base_id, vrf_base_id + vrf_count) | map('regex_replace', '^', vrf_base_name) | list }}"

    - name: Check VLAN configurations
      arista.eos.eos_command:
        commands:
          - show vlan
      register: show_vlan_output

    - name: Validate VLAN configurations
      set_fact:
        vlan_results: "{{ vlan_results + ['VLAN ' ~ item ~ ' - configuration ' ~ ('OK' if 'VLAN_' ~ item in show_vlan_output.stdout[0] else 'Fail')] }}"
      loop: "{{ range(vlan_base_id, vlan_base_id + vlan_count) | list }}"

    - name: Display VRF configuration results
      debug:
        msg: "{{ vrf_results }}"

    - name: Display VLAN configuration results
      debug:
        msg: "{{ vlan_results }}"
