---
- name: Configure VRFs and VLANs on Arista EOS devices
  hosts: arista_node
  gather_facts: no
  vars_files:
    - vars/variable.yml

  tasks:
    - name: Configure all VRFs in one task
      arista.eos.eos_config:
        lines: "{% for vrf, rd in vrfs | zip(rds) %}vrf instance {{ vrf }}\nrd {{ rd }}\ndescription Description for {{ vrf }}\n{% endfor %}"
        match: none
        save_when: modified

    - name: Configure all VLANs in one task
      arista.eos.eos_config:
        lines: "{% for vlan, description in vlans | zip(vlan_descriptions) %}vlan {{ vlan }}\nname {{ description }}\n{% endfor %}"
        match: none
        save_when: modified
