---
- name: Remove VRFs and VLANs on Arista EOS devices
  hosts: arista_node
  gather_facts: no
  vars_files:
    - variable.yml

  tasks:
    - name: Remove all VRFs in one task
      arista.eos.eos_config:
        lines: "{% for vrf in vrfs %}no vrf instance {{ vrf }}\n{% endfor %}"
        match: none
        save_when: modified

    - name: Remove all VLANs in one task
      arista.eos.eos_config:
        lines: "{% for vlan in vlans %}no vlan {{ vlan }}\n{% endfor %}"
        match: none
        save_when: modified
